name: Deploy Ubuntu VM to Azure
on:
  push:
    branches:
      - main
jobs:
  deploy-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
                        az group create --name myResourceGroup --location eastus
      - name: Deploy VM
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          resourceGroupName: myResourceGroup
          template: ./azuredeploy.json
          parameters: ./azuredeploy.parameters.json
          failOnStdErr: true
